import type { NextPage } from 'next'
import Head from 'next/head'
import {useEffect, useState} from 'react';
import styles from '../styles/Home.module.css'


const title = '♥ Bazel + Skaffold ♥';
const Home: NextPage = () => {

  const [greeting, setGreeting] = useState('');

  useEffect(() => {
    fetch('/api/v1/greeting')
    .then(res => res.json())
    .then((result) => {
      setGreeting(result.greeting);
    })

  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {title}
        </h1>

        <h3>{greeting}</h3>

        <p>Go make some changes and watch the magic!</p>
      </main>

      <footer className={styles.footer}>
        <a rel="author" href="https://github.com/ddlees">Brought to you by Dillon Lees</a>
      </footer>
    </div>
  )
}

export default Home
