apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  clusterIP: None
  ports:
    - port: 8080
      name: api
  selector:
    app: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: api
        ports:
        - containerPort: 8080
          name: http
